Fix crash on methods declared as independently generic
This doesn't yet support inferring types on methods which are generic
based on their parameter, but at least avoids crashing when they are
defined:

```
/Users/broz/src/solargraph/lib/solargraph/complex_type/unique_type.rb:71:in `resolve_generics': undefined method `generics' for an instance of Solargraph::Pin::Method (NoMethodError)

          idx = definitions.generics.index(subtypes.first&.name)
                           ^^^^^^^^^
	from /Users/broz/src/solargraph/lib/solargraph/complex_type.rb:118:in `block in resolve_generics'
	from /Users/broz/src/solargraph/lib/solargraph/complex_type.rb:118:in `map'
	from /Users/broz/src/solargraph/lib/solargraph/complex_type.rb:118:in `resolve_generics'
	from /Users/broz/src/solargraph/lib/solargraph/source/chain.rb:132:in `block in infer_first_defined'
	from /Users/broz/src/solargraph/lib/solargraph/source/chain.rb:123:in `each'
	from /Users/broz/src/solargraph/lib/solargraph/source/chain.rb:123:in `infer_first_defined'
        from /Users/broz/src/solargraph/lib/solargraph/source/chain.rb:85:in `infer'
```